/**
 * Created by lijian on 2017/4/22.
 */
export const CHANGE_SSQ_PLAY_TYPE = 'CHANGE_SSQ_PLAY_TYPE'

export const INITIAL_SSQ_DS_STATE = 'INITIAL_SSQ_DS_STATE'

export const CHOICE_RED_BALL_SSQ_DS = 'CHOICE_RED_BALL_SSQ_DS'
export const CHOICE_BLUE_BALL_SSQ_DS = 'CHOICE_BLUE_BALL_SSQ_DS'
export const CALCULATION_BETNOTE_SSQ_DS = 'CALCULATION_BETNOTE_SSQ_DS'

export const CHANGE_BET_NOTE = 'CHANGE_BET_NOTE'

export const MACHINE_SELECTION_SSQ_DS = 'MACHINE_SELECTION_SSQ_DS'
